# k8s/secrets.yaml
# IMPORTANT : Ne jamais committer ce fichier sur Git
# Ajouter secrets.yaml dans .gitignore
apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
  namespace: mern-prod
type: Opaque
stringData:
  MONGO_URI: 'mongodb+srv://lovanomeny72:noumsnahitan@cluster0.1v9g1rg.mongodb.net/?appName=Cluster0'
  JWT_SECRET: 'xt713j7at9wluk3rnakvcu5ri'
